import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      'xs':  '375px',
      'sm':  '640px',
      'md':  '768px',
      'lg':  '1024px',
      'xl':  '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        primary: {
          50:  '#E8F5E9',
          100: '#C8E6C9',
          200: '#A5D6A7',
          300: '#81C784',
          400: '#66BB6A',
          500: '#4CAF50',
          600: '#04AA6D',
          700: '#388E3C',
          800: '#2E7D32',
          900: '#1B5E20',
        },
        w3dark:  '#282A35',
        w3mid:   '#3d3f4e',
        surface: '#F9F9F9',
        sidebar: '#282A35',
        brand:   '#04AA6D',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        '3xs': ['0.55rem', { lineHeight: '0.8rem' }],
      },
      borderRadius: {
        DEFAULT: '4px',
        sm:   '2px',
        md:   '4px',
        lg:   '6px',
        xl:   '8px',
        '2xl':'12px',
        '3xl':'16px',
        '4xl':'24px',
      },
      spacing: {
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-top':    'env(safe-area-inset-top, 0px)',
      },
      minHeight: {
        'tap': '44px',
      },
      minWidth: {
        'tap': '44px',
      },
      boxShadow: {
        'sm':     '0 1px 2px 0 rgba(0,0,0,0.06)',
        'card':   '0 1px 3px 0 rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)',
        'md':     '0 4px 6px -1px rgba(0,0,0,0.08), 0 2px 4px -2px rgba(0,0,0,0.04)',
        'lg':     '0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -4px rgba(0,0,0,0.04)',
        'xl':     '0 20px 25px -5px rgba(0,0,0,0.10), 0 8px 10px -6px rgba(0,0,0,0.04)',
        'glow':   '0 0 0 3px rgba(4,170,109,0.15)',
        'glow-lg':'0 0 20px rgba(4,170,109,0.2)',
        'lift':   '0 8px 24px rgba(0,0,0,0.09)',
        'bottom-nav': '0 -4px 20px rgba(0,0,0,0.08)',
      },
      transitionTimingFunction: {
        'spring':  'cubic-bezier(0.34,1.56,0.64,1)',
        'smooth':  'cubic-bezier(0.22,1,0.36,1)',
        'bounce':  'cubic-bezier(0.34,1.56,0.64,1)',
      },
      animation: {
        'fade-in':       'fadeIn 0.2s ease-out',
        'fade-in-up':    'fadeInUp 0.3s cubic-bezier(0.22,1,0.36,1)',
        'float-up':      'floatUp 0.35s cubic-bezier(0.22,1,0.36,1)',
        'float-card':    'floatCard 0.45s cubic-bezier(0.22,1,0.36,1)',
        'slide-up':      'slideUp 0.25s ease-out',
        'slide-left':    'slideInLeft 0.28s cubic-bezier(0.22,1,0.36,1)',
        'slide-bottom':  'slideInBottom 0.3s cubic-bezier(0.22,1,0.36,1)',
        'scale-in':      'scaleIn 0.2s ease-out',
        'modal-in':      'modalIn 0.28s cubic-bezier(0.22,1,0.36,1)',
        'shimmer':       'shimmer 1.3s infinite linear',
        'spin-slow':     'spin 0.65s linear infinite',
        'pulse-dot':     'pulse-dot 1.6s ease-in-out infinite',
        'success-pop':   'successPop 0.4s cubic-bezier(0.34,1.56,0.64,1)',
        'count-up':      'countUp 0.35s ease-out',
        'shake':         'shake 0.4s ease-in-out',
        'ripple':        'rippleEffect 0.5s ease-out forwards',
        'bounce-icon':   'bounceIcon 2.5s ease-in-out infinite',
        'gradient':      'gradientShift 6s ease infinite',
        'glow-pulse':    'glowPulse 2s ease infinite',
        'nav-highlight': 'navHighlight 0.2s ease-out',
        'tab-slide':     'tabSlide 0.2s ease-out',
      },
      keyframes: {
        fadeIn:        { from:{ opacity:'0' }, to:{ opacity:'1' } },
        fadeInUp:      { from:{ opacity:'0', transform:'translateY(12px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        floatUp:       { from:{ opacity:'0', transform:'translateY(20px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        floatCard:     { from:{ opacity:'0', transform:'translateY(24px) scale(0.98)' }, to:{ opacity:'1', transform:'translateY(0) scale(1)' } },
        slideUp:       { from:{ opacity:'0', transform:'translateY(6px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        slideInLeft:   { from:{ opacity:'0', transform:'translateX(-100%)' }, to:{ opacity:'1', transform:'translateX(0)' } },
        slideInBottom: { from:{ opacity:'0', transform:'translateY(100%)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        scaleIn:       { from:{ opacity:'0', transform:'scale(0.92)' }, to:{ opacity:'1', transform:'scale(1)' } },
        modalIn:       { from:{ opacity:'0', transform:'scale(0.88) translateY(16px)' }, to:{ opacity:'1', transform:'scale(1) translateY(0)' } },
        'pulse-dot':   { '0%,100%':{ opacity:'1' }, '50%':{ opacity:'.3' } },
        successPop:    { '0%':{ transform:'scale(0.7)', opacity:'0' }, '60%':{ transform:'scale(1.15)' }, '100%':{ transform:'scale(1)', opacity:'1' } },
        countUp:       { from:{ transform:'translateY(8px)', opacity:'0' }, to:{ transform:'translateY(0)', opacity:'1' } },
        shimmer:       { '0%':{ backgroundPosition:'-600px 0' }, '100%':{ backgroundPosition:'600px 0' } },
        shake:         { '0%,100%':{ transform:'translateX(0)' }, '15%,45%':{ transform:'translateX(-5px)' }, '30%,60%':{ transform:'translateX(5px)' }, '75%':{ transform:'translateX(-3px)' }, '90%':{ transform:'translateX(3px)' } },
        rippleEffect:  { from:{ transform:'scale(0)', opacity:'0.5' }, to:{ transform:'scale(4)', opacity:'0' } },
        gradientShift: { '0%':{ backgroundPosition:'0% 50%' }, '50%':{ backgroundPosition:'100% 50%' }, '100%':{ backgroundPosition:'0% 50%' } },
        bounceIcon:    { '0%,100%':{ transform:'translateY(0)' }, '30%':{ transform:'translateY(-10px)' }, '60%':{ transform:'translateY(-4px)' }, '80%':{ transform:'translateY(-7px)' } },
        glowPulse:     { '0%,100%':{ boxShadow:'0 0 0 0 rgba(4,170,109,0.3)' }, '50%':{ boxShadow:'0 0 0 6px rgba(4,170,109,0)' } },
        navHighlight:  { from:{ transform:'scaleX(0.6)', opacity:'0' }, to:{ transform:'scaleX(1)', opacity:'1' } },
        tabSlide:      { from:{ transform:'scaleX(0)', opacity:'0' }, to:{ transform:'scaleX(1)', opacity:'1' } },
      },
    },
  },
  plugins: [],
}
export default config
